### ISSUE TITLE
MedicationTest patient breaks Pharma workflow

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/htnu18ig#110]
for some reason, the MedicationTest patient in the Logica Sandbox is breaking the Pharma workflow (issue first identified 5/10/2022).  the only thing special about this patient is that they have a few different kinds of medications, but COACH doesn't send medications to cqf-ruler; cqf-ruler obtains medications independently.  so the problem can't be in COACH.

working with cqf-ruler 1.4.1.

![image](https://user-images.githubusercontent.com/979938/175612333-ccdfec21-aca4-46cd-838a-69a54d25da0c.png)

error text:

> ERROR: Exception in CQL Execution.Expected a list with at most one element, but found a list with multiple elements.org.opencds.cqf.cql.engine.exception.InvalidOperatorArgument: Expected a list with at most one element, but found a list with multiple elements. at org.opencds.cqf.cql.engine.elm.execution.SingletonFromEvaluator.singletonFrom(SingletonFromEvaluator.java:32) at org.opencds.cqf.cql.engine.elm.execution.SingletonFromEvaluator.internalEvaluate(SingletonFromEvaluator.java:47) at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18) at org.opencds.cqf.cql.engine.elm.execution.QueryEvaluator.evaluateLets(QueryEvaluator.java:35) at org.opencds.cqf.cql.engine.elm.execution.QueryEvaluator.internalEvaluate(QueryEvaluator.java:191) at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18) at org.opencds.cqf.cql.engine.elm.execution.ExpressionDefEvaluator.internalEvaluate(ExpressionDefEvaluator.java:19) at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18) at org.opencds.cqf.cql.engine.elm.execution.ExpressionRefEvaluator.internalEvaluate(ExpressionRefEvaluator.java:11) at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18) at org.opencds.cqf.cql.engine.elm.execution.QueryEvaluator.internalEvaluate(QueryEvaluator.java:165) at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18) at org.opencds.cqf.cql.engine.elm.execution.QueryEvaluator.internalEvaluate(QueryEvaluator.java:165) at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18) at org.opencds.cqf.cql.engine.elm.execution.AnyInValueSetEvaluator.internalEvaluate(AnyInValueSetEvaluator.java:10) at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18) at org.opencds.cqf.cql.engine.elm.execution.ExpressionDefEvaluator.internalEvaluate(ExpressionDefEvaluator.java:19) at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18) at org.opencds.cqf.cql.engine.elm.execution.ExpressionRefEvaluator.internalEvaluate(ExpressionRefEvaluator.java:11) at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18) at org.opencds.cqf.cql.engine.elm.execution.IfEvaluator.internalEvaluate(IfEvaluator.java:9) at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18) at org.opencds.cqf.cql.engine.elm.execution.ExpressionDefEvaluator.internalEvaluate(ExpressionDefEvaluator.java:19) at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18) at org.opencds.cqf.cds.hooks.R4HookEvaluator.resolveActions(R4HookEvaluator.java:148) at org.opencds.cqf.cds.hooks.R4HookEvaluator.evaluateCdsHooksPlanDefinition(R4HookEvaluator.java:53) at org.opencds.cqf.cds.hooks.R4HookEvaluator.evaluateCdsHooksPlanDefinition(R4HookEvaluator.java:1) at org.opencds.cqf.cds.hooks.BaseHookEvaluator.evaluate(BaseHookEvaluator.java:73) at org.opencds.cqf.r4.servlet.CdsHooksServlet.doPost(CdsHooksServlet.java:211) at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319) at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191) at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.Server.handle(Server.java:516) at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) at java.base/java.lang.Thread.run(Thread.java:871)

relevant server logs and CQL:
[MedicationTest-Pharma-error-logs-and-cql.txt](https://github.com/OHSUCMP/htnu18ig/files/8978839/MedicationTest-Pharma-error-logs-and-cql.txt)

I think the issue has to do with something in this part of the code in OHSUHTNCommon.cql:

```
define "Patient is Using Antihypertensive Medications":
  "Medication Requests With Medication".medication in "Antihypertensive Medications"

valueset "Antihypertensive Medications": 'http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1178.10'

define "Medication Requests With Medication":
  "Active Medication Requests" Rx
    let medication: singleton from ([Medication: id in Last(Split(Rx.medication.reference, '/'))])
    return
      MedicationRequest {
        id: Rx.id,
        status: Rx.status,
        intent: Rx.intent,
        category: Rx.category,
        medication: medication.code,
        subject: Rx.subject,
        authoredOn: Rx.authoredOn,
        recorder: Rx.recorder,
        dosageInstruction: Rx.dosageInstruction,
        dispenseRequest: Rx.dispenseRequest
      }
```

I tried to dig into the CQL via "cql_logging_enabled" flag (see https://github.com/DBCG/cqf-ruler/pull/338) which I actually wrote, but for some fun reason, I've had a lot of trouble getting any debug logging to show up.  Maybe an issue with logback?  I can see that the flag is set, but no debug logs are generated that I can see.  I have no idea why.

Anyway, so I'm tabling this for now to come back to it later.

**Comment by mattStorer** [comment]
got debug logging to work, yay!

**Comment by mattStorer** [comment]
relevant cqf-ruler logs including CQL debug data:
[MedicationTest-Pharma-cqldebug.txt](https://github.com/OHSUCMP/htnu18ig/files/8979872/MedicationTest-Pharma-cqldebug.txt)

**Comment by aeyates** [comment]
This patient has MedicationRequests that are not formatted as expected in the CQL. In order to get both the request and the underlying medication, Bryn provided us this bit of CQL for constructing the query:

```
define "Medication Requests With Medication":
  "Active Medication Requests" Rx
    let medication: singleton from ([Medication: id in Last(Split(Rx.medication.reference, '/'))])
    return
      MedicationRequest {
        id: Rx.id,
        status: Rx.status,
        intent: Rx.intent,
        category: Rx.category,
        medication: medication.code,
        subject: Rx.subject,
        authoredOn: Rx.authoredOn,
        recorder: Rx.recorder,
        dosageInstruction: Rx.dosageInstruction,
        dispenseRequest: Rx.dispenseRequest
      }
```

This expects that the request will have a medication reference and not a medicationCodeableConcept, although the FHIR standard supports either (https://www.hl7.org/fhir/medicationrequest.html).

2 of the requests for this patient have a CodeableConcept and not a Reference. For example:

{
  "resourceType": "MedicationRequest",
  "id": "medicationRequest-MedicationTest-2",
  "meta": {
    "versionId": "2",
    "lastUpdated": "2021-08-24T23:27:22.000+00:00",
    "source": "#KyYyEQj3F24SP8bx"
  },
  "status": "active",
  "intent": "order",
  "medicationCodeableConcept": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "1014599",
        "display": "acetaminophen 300 MG / oxycodone hydrochloride 10 MG Oral Tablet"
      }
    ],
    "text": "acetaminophen 300 MG / oxycodone hydrochloride 10 MG Oral Tablet"
  },
  "subject": {
    "reference": "Patient/MedicationTest"
  },
  "authoredOn": "2021-05-01T16:00:00-08:00",
  "note": [
    {
      "text": "all opioids valueset"
    }
  ]
}

I can play with this a bit to see if we can incorporate both possibilities within the query.

**Comment by aeyates** [comment]
OK, this has been fixed in the dev branch @mattStorer , and I have tested it with COACH running locally:

<img width="1080" alt="Screen Shot 2022-08-16 at 3 58 38 PM" src="https://user-images.githubusercontent.com/2576491/184999538-6443de5a-0164-486f-88f9-be39d81f8b8f.png">

**Comment by aeyates** [comment]
It should be noted that Medications in the prefetch are ignored and CQF Ruler will always expect a reference to a Medication to exist on the EHR server. This makes sense, but can be confusing in testing when we are trying to encapsulate everything in the prefetch to avoid querying the EHR.
