### ISSUE TITLE
Automated build is no longer working

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/htnu18ig#216]
Michelle reported that the build.fhir.org site for the IG was no longer up.

**Comment by aeyates** [comment]
Here’s the repo describing the builder and how to use it: https://github.com/FHIR/auto-ig-builder?tab=readme-ov-file
 
And here’s the repo that walks through installing the builder into an existing IG: https://github.com/apps/fhir-ig-builder

I do not have the proper permissions for OHSUCMP to see or manage any information about the automated FHIR builder, so I can not determine whether it is still installed and whether it is providing errors. @mattStorer will need to look at this.

I can, however, confirm that the IG is no longer building locally and this is probably what is preventing it from being hosted. These are the instructions I wrote for building the IG when I originally figured out how to do it:

[Publishing the IG locally](https://ohsuitg-my.sharepoint.com/:w:/r/personal/dunnem_ohsu_edu/Documents/From_Box/COACH%20High%20Blood%20Pressure/IG%20Development%20Documentation/Publishing%20the%20IG%20Locally.docx?d=wcdc3eeefd55b4650b9c15b820a8f5ac4&csf=1&web=1&e=NsTAoz)

When I try to build the IG locally, I get the error message “The package 'cqf.fhir.template' has no entry on the current build server”. I had a vague memory of this problem and found a commit Matt made in 2022. I tracked down this email from Bryn in January of 2022 when he suggested we needed to use a different template in our ig.ini file:

```
Hi Matt,

What's happening is that the footer is being built by the template, and so the license is established. You're using the hl7.fhir.template, which is actually the template for balloted HL7 content, and as an open source, non-HL7 project, you shouldn't be using that template. I can recommend the CQF template, which will not only let you change the footer as needed, but also change the branding (it's important to make sure that only HL7-balloted/published content has HL7 branding).

So if you change the template entry in your ig.ini to use cqf.fhir.template:

[https://github.com/cqframework/cqf/blob/master/ig.ini#L3](https://urldefense.com/v3/__https://github.com/cqframework/cqf/blob/master/ig.ini*L3__;Iw!!Mi0JBg!aFQgZiUhell_lukdFgJevcJSh_LgdK26C08v1j-XYxqelcH2EfwNYqiQpNkZsFA$)

(If you get errors building that, remove the #current qualifier)

Then the license footer should point to the license.html in your local. Let me know if that doesn't work.

Regards,
Bryn Rhodes
[bryn@alphora.com](mailto:bryn@alphora.com)
```

When I go to the Github link Bryn referenced, I notice that the ini file no longer refers to the "current" version but instead to 0.6.0. Making that change allows us to build locally.

```
template = cqf.fhir.template#0.6.0
```

I will try pushing this change to master to see if it resolves the problem.

**Comment by aeyates** [comment]
The change appears to have done the trick. You can navigate here to see all igs being built successfully:

https://build.fhir.org/ig/

It is also seen here now:

https://fhir.github.io/auto-ig-builder/

**Comment by mattStorer** [comment]
Not sure when the auto-build ended, but I was able to install the auto-ig-builder application into the htnu18ig repo (it was not previously installed).

builds will be documented here when they occur: https://chat.fhir.org/#narrow/stream/179297-committers.2Fnotification/topic/ig-build
